FROM node:16-alpine
WORKDIR '/app'
COPY ./package.json .
RUN npm install
COPY . .
CMD ["npm", "run", "start"]

# #Log in to the doker CLI
# echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# #TAKE those iages and push them to docker hub
# docker push {image}