sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t millennium133/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true millennium133/react-test npm test

after_success:
  - docker build -t millennium133/multi-client ./client
  - docker build -t millennium133/multi-nginx ./nginx
  - docker build -t millennium133/multi-server ./server
  - docker build -t millennium133/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push millennium133/multi-client
  - docker push millennium133/multi-nginx
  - docker push millennium133/multi-server
  - docker push millennium133/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'multi-docker'
  env: 'Multi-Docker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-654654145031'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY